### ISSUE TITLE
Can't compile on Ubuntu 19.10

### ISSUE THREAD

**Issue by guillaumedavidphd** [toastpp/toastpp#69]
Hello,
I've been trying to compile Toast++ to no avail. I keep getting the following error:
`/usr/include/math.h:1050:16: error: no match for ‘operator==’ (operand types are ‘std::complex<float>’ and ‘int’)`
` 1050 |   return __val == 0;`
Any idea what this is?
I'm running a fresh install of Ubuntu 19.10, compiling with `gcc`, `g++`, and `gfortran` version `9.2.1`. To get to this error, I'm taking the following steps in the Toast++ root directory:

- `export TOASTDIR=$PWD`
- `./configure`
- `source toastenv.sh`
- `make numerics -j6`
- `make toast -j6`

`numerics` seems to build OK, the error is when I try to build `toast`. I can provide more information if need be. 
-Guillaume

**Comment by samuelpowell** [comment]
See #66
